### ISSUE TITLE
SoundPoint 335 with SIP Firmware 4.0.10

### ISSUE THREAD

**Issue by renemorenotx** [tony722/3CXPolycomLegacy#3]
Hello,
I tried a soundpoint 335 with 3cx. Do you have an xml file that would work with firmware 4.0.10?

**Comment by tony722** [comment]
Sorry I don't, and I'm not using 3CX anymore. I'm using FreePBX which I like a lot better because I can configure it to do the things we need--it has more features, and is more configurable.
